### ISSUE TITLE
ITree Roadmap

### ISSUE THREAD

**Issue by i-walker** [i-walker/arend-exercises#13]
Though Arend doesn't support coinductive types natively, this roadmap tracks the steps toward verifying an Interaction Tree draft in Arend. 

The objects are: 
- [ ] Define the Interaction Tree with all its operations, in this [paper](https://github.com/i-walker/arend-exercises/blob/master/src/papers/itrees/Itrees.pdf)
- [ ] Verify its behavior with typeclasses proofs
- [ ] **Optional:** Define necessary proofs to allow equational reasoning
